name: Build Plugins
permissions: 
  contents: read

on:
  push:
    paths:
      - 'Artemis.Plugins*/**'
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 */3 *'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Clone
        uses: actions/checkout@v4

      - name: Build
        run: dotnet publish -c Release Artemis.Plugins.jonilala796.sln

      - name: Upload Nanoleaf Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artemis.Plugins.Devices.Nanoleaf
          path: Artemis.Plugins.Devices.Nanoleaf/bin/x64/Release/net10.0/publish      
            
      - name: Upload DateTime Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Artemis.Plugins.Nodes.DateTime
          path: Artemis.Plugins.Nodes.DateTime/bin/x64/Release/net10.0/publish

      - name: Install Plugin Uploader
        run: dotnet tool install ArtemisRGB.Tools.PluginUploader --global

      - name: Upload Nanoleaf Plugin to Artemis Workshop
        if: github.ref == 'refs/heads/main'
        run: artemis-plugin-uploader upload-all --pat ${{ secrets.WORKSHOP_PAT }} --folder Artemis.Plugins.Devices.Nanoleaf/bin/x64/Release/net10.0

      - name: Upload DateTime Plugin to Artemis Workshop
        if: github.ref == 'refs/heads/main'
        run: artemis-plugin-uploader upload-all --pat ${{ secrets.WORKSHOP_PAT }} --folder Artemis.Plugins.Nodes.DateTime/bin/x64/Release/net10.0
